### ISSUE TITLE
error al compilar el proyecto

### ISSUE THREAD

**Issue by jvelezb** [Andres-CT/ReporteDeFugas#12]
![Captura de Pantalla 2020-05-12 a la(s) 11 25 56 p  m](https://user-images.githubusercontent.com/1113708/81771201-fa6b3280-94a7-11ea-8add-ef1c9e12be91.png)

**Comment by jorgedelavg04** [comment]
corregido el error, se encontraba declarado un html que no usábamos, ni teníamos.
